#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@openclash[-1]
	add ucitrack openclash
	set ucitrack.@openclash[-1].init=openclash
	commit ucitrack

	delete firewall.openclash
	set firewall.openclash=include
	set firewall.openclash.type=script
	set firewall.openclash.path=/var/etc/openclash.include
	set firewall.openclash.family=any
	set firewall.openclash.reload=1
	commit firewall
EOF

exit 0
