#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@openclash[-1]
	add ucitrack openclash
	set ucitrack.@openclash[-1].init=openclash
	commit ucitrack

	delete firewall.openclash
	set firewall.openclash=include
	set firewall.openclash.type=script
	set firewall.openclash.path=/var/etc/openclash.include
	set firewall.openclash.reload=1
	commit firewall
EOF

mkdir -p ${IPKG_INSTROOT}/etc/openclash/config
mkdir -p ${IPKG_INSTROOT}/etc/openclash/proxy_provider
mkdir -p ${IPKG_INSTROOT}/etc/openclash/rule_provider
mkdir -p ${IPKG_INSTROOT}/etc/openclash/backup
mkdir -p ${IPKG_INSTROOT}/etc/openclash/core
mkdir -p ${IPKG_INSTROOT}/usr/share/openclash/backup

exit 0
