#!/bin/sh /etc/rc.common

START=90
STOP=10

USE_PROCD=1
NICEPRIO=19

PROG=/usr/bin/syncthing

section_enabled() {
	config_get_bool enabled "$1" enabled 0
	[ $enabled -gt 0 ]
}

start_instance() {
	section_enabled "$section" || return 1

	config_get gui_address syncthing gui_address "0.0.0.0:8384"
	config_get home syncthing home "/etc/syncthing/"
	config_get logfile syncthing logfile "/var/log/syncthing.log"

	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command -gui-address="$gui_address"
	procd_append_param command -home="$home"
	procd_append_param command -logfile="$logfile"
	procd_set_param respawn
	procd_set_param nice "$NICEPRIO"
	procd_close_instance
}

start_service() {
	config_load 'syncthing'
	config_foreach start_instance 'syncthing'
}

service_triggers() {
	procd_add_reload_trigger "syncthing"
}
