#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dnsforwarder[-1]
	add ucitrack dnsforwarder
	set ucitrack.@dnsforwarder[-1].init=dnsforwarder
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
