#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.softethervpn
	set firewall.softethervpn=include
	set firewall.softethervpn.type=script
	set firewall.softethervpn.path=/usr/share/softethervpn/firewall.include
	set firewall.softethervpn.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softethervpn[-1]
	add ucitrack softethervpn
	set ucitrack.@softethervpn[-1].init=softethervpnserver
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
