#!/bin/sh

# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@appfilter[-1]
	add ucitrack appfilter
	set ucitrack.@appfilter[-1].exec="/etc/init.d/appfilter reload"
	commit ucitrack
EOF

exit 0
