include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for XLNetAcc
LUCI_DEPENDS:=+luci-compat +jshn +wget +openssl-util
PKG_VERSION:=1.0.5
PKG_RELEASE:=1

PKG_LICENSE:=GPLv2
PKG_MAINTAINER:=Sense <sensec@gmail.com>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
