#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Control the ACME Letsencrypt certificate interface
LUCI_DEPENDS:=+luci-compat +luci-mod-admin-full +acme-dnsapi

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
