#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.ipsecvpn
	set firewall.ipsecvpn=include
	set firewall.ipsecvpn.type=script
	set firewall.ipsecvpn.path=/usr/share/ipsecvpn/firewall.include
	set firewall.ipsecvpn.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ipsec[-1]
	add ucitrack ipsec
	set ucitrack.@ipsec[-1].init=ipsec
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
