#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@v2ray[-1]
	add ucitrack v2ray
	set ucitrack.@v2ray[-1].init=v2ray
	commit ucitrack

	delete firewall.v2ray
	set firewall.v2ray=include
	set firewall.v2ray.type=script
	set firewall.v2ray.path=/etc/firewall.v2ray
	set firewall.v2ray.family=any
	set firewall.v2ray.reload=1
	commit firewall
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
