#!/bin/sh

# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@mwan3[-1]
	add ucitrack mwan3
	set ucitrack.@mwan3[-1].exec="/etc/init.d/mwan3 reload"
	commit ucitrack
EOF

exit 0
